version: '3.8'

services:
  movies_microservice_mysql:
    build:
      dockerfile: movies-microservice-mysql/Dockerfile
      context: .
    depends_on:
      - movies_db_mysql
    ports:
      - '8000:8000'
    env_file:
      - movies-microservice-mysql/.env

  movies_db_mysql:
    image: mysql:latest
    restart: always
    container_name: movies_db_mysql
    environment:
      MYSQL_DATABASE: 'movies-app'
      MYSQL_ROOT_USER: 'root'
      MYSQL_PASSWORD: 'Alarak19*'
      MYSQL_ROOT_PASSWORD: 'Alarak19*'
    ports:
      - '3306:3306'
    expose:
      - '3306'

  movies_db_mongodb:
    image: mongo:latest
    restart: always
    container_name: movies_db_mongodb
    ports:
      - '27017:27017'    

  movies_rabbitmq:
    image: rabbitmq:latest
    container_name: movies_rabbitmq
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_network

  movies_microservice_mongodb:
    build: 
      dockerfile: movies-microservice-mongodb/Dockerfile
      context: .
    depends_on:
      - movies_db_mongodb
    ports:
      - '8001:8001'

  movies_microservice_mongodb_listener:
    build:
      dockerfile: movies-microservice-mongodb/ListenerDockerfile
      context: .

networks:
  rabbitmq_network:
    driver: bridge

  

