version: '3.8'

services:
  movies-microfrontend-shell:
    build:
      context: .
      dockerfile: projects/shell/ShellDockerfile
      args:
        ANGULAR3_APP_API_BASE_URL: http://127.0.0.1:5000/
    ports:
      - "5000:80"
    links:
      - movies-microfrontend-mf1
      - movies-microfrontend-mf2
    container_name: movies-microfrontend-shell
    stdin_open: true

  movies-microfrontend-mf1:
    build:
      context: .
      dockerfile: projects/mf1/Mf1Dockerfile
      args:
        ANGULAR1_APP_API_BASE_URL: http://127.0.0.1:3000/remoteEntry.js
    ports:
      - "3000:8080"
    container_name: movies-microfrontend-mf1
    stdin_open: true

  movies-microfrontend-mf2:
    build:
      context: .
      dockerfile: projects/mf2/Mf2Dockerfile
      args:
        ANGULAR2_APP_API_BASE_URL: http://127.0.0.1:3001/remoteEntry.js
    ports:
      - "3001:8080"
    links:
      - movies-microfrontend-mf1
    container_name: movies-microfrontend-mf2
    stdin_open: true